#!/bin/sh
set -ex
PKG_TOPDIR=$(cd $(dirname $0) && pwd -P)
PKG_NAME=measurement-kit
PKG_VERSION=0.10.3
PKG_CHECKSUM=04bc1832fbaa54a9fde4923e8f44a2f99610a862c228dd05977c36f54870d80f
PKG_URL=https://github.com/measurement-kit/measurement-kit/archive/v$PKG_VERSION.tar.gz
PKG_BUILD=+1
[ "$PKG_OS" != "" -a "$PKG_ARCH" != "" ]
PKG_FULLNAME=$PKG_NAME/$PKG_VERSION$PKG_BUILD
PKG_BUILDDIR=$PKG_TOPDIR/MK_BUILD/$PKG_OS/$PKG_FULLNAME/$PKG_ARCH
PKG_INSTALLDIR=$PKG_TOPDIR/MK_DIST/$PKG_OS/$PKG_FULLNAME/$PKG_ARCH
PKG_CURL_VERSION=7.64.1+2
PKG_LIBEVENT_VERSION=2.1.8+6
PKG_LIBMAXMINDDB_VERSION=1.3.2+5
PKG_LIBRESSL_VERSION=2.9.1+1
rm -rf $PKG_BUILDDIR $PKG_INSTALLDIR
install -d $PKG_BUILDDIR $PKG_INSTALLDIR
(
  set -ex
  cd $PKG_BUILDDIR
  curl -fsSLO $PKG_URL
  REAL_CHECKSUM=$(shasum -a 256 v$PKG_VERSION.tar.gz | awk '{print $1}')
  [ $PKG_CHECKSUM = "$REAL_CHECKSUM" ]
  tar -xzf v$PKG_VERSION.tar.gz
  cd $PKG_NAME-$PKG_VERSION
  ./autogen.sh -n
  CURL_PREFIX=$PKG_TOPDIR/MK_DIST/$PKG_OS/curl/$PKG_CURL_VERSION/$PKG_ARCH/
  LIBEVENT_PREFIX=$PKG_TOPDIR/MK_DIST/$PKG_OS/libevent/$PKG_LIBEVENT_VERSION/$PKG_ARCH/
  LIBMAXMINDDB_PREFIX=$PKG_TOPDIR/MK_DIST/$PKG_OS/libmaxminddb/$PKG_LIBMAXMINDDB_VERSION/$PKG_ARCH/
  LIBRESSL_PREFIX=$PKG_TOPDIR/MK_DIST/$PKG_OS/libressl/$PKG_LIBRESSL_VERSION/$PKG_ARCH/
  ./configure --prefix=/ --disable-dependency-tracking                         \
    --with-libevent=$LIBEVENT_PREFIX --with-openssl=$LIBRESSL_PREFIX           \
    --with-libcurl=$CURL_PREFIX --with-libmaxminddb=$LIBMAXMINDDB_PREFIX       \
    $PKG_CONFIGUREFLAGS CPPFLAGS="$CPPFLAGS -Wno-cpp"
  make libmeasurement_kit.la V=0
  make install-libLTLIBRARIES install-data-am DESTDIR=$PKG_INSTALLDIR
  rm -rf $PKG_INSTALLDIR/lib/libmeasurement_kit.la
  rm -rf $PKG_INSTALLDIR/include/measurement_kit/README.md
)
